# Generated by Django 3.1.7 on 2021-03-13 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='albergues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_albergue', models.CharField(max_length=50)),
                ('ciudad', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=1000)),
                ('referencia', models.CharField(max_length=11000)),
                ('duena', models.CharField(max_length=100)),
                ('responsable', models.CharField(max_length=100)),
                ('cuidador', models.CharField(max_length=100)),
                ('dias_atencion', models.CharField(max_length=100)),
                ('horario_atencion', models.CharField(max_length=100)),
                ('fecha_ingreso_matchcota', models.DateField()),
                ('vigente', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_color', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='distrito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_postal', models.CharField(max_length=30)),
                ('nombre_distrito', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='mascotas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_carnet', models.CharField(max_length=20)),
                ('nombre_mascota', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=10)),
                ('f_registro_matchcota', models.DateField()),
                ('f_ingreso_albergue', models.DateField()),
                ('f_nacimiento', models.DateField()),
                ('f_fallecimiento', models.DateField()),
                ('microchip', models.CharField(max_length=15)),
                ('activo_web', models.CharField(max_length=2)),
                ('id_albergue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MatchApp.albergues')),
                ('id_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MatchApp.estado')),
            ],
        ),
        migrations.CreateModel(
            name='personalidad_perro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carinoso', models.CharField(max_length=2)),
                ('curioso', models.CharField(max_length=2)),
                ('deportista', models.CharField(max_length=2)),
                ('educado', models.CharField(max_length=2)),
                ('independiente', models.CharField(max_length=2)),
                ('jugueton', models.CharField(max_length=2)),
                ('tranquilo', models.CharField(max_length=2)),
                ('relacion_p_hembras', models.CharField(max_length=2)),
                ('relacion_p_machos', models.CharField(max_length=2)),
                ('relacion_p_humanos', models.CharField(max_length=2)),
                ('id_mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MatchApp.mascotas')),
            ],
        ),
        migrations.CreateModel(
            name='personalidad_gato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sociable_humanos', models.CharField(max_length=2)),
                ('amigable', models.CharField(max_length=2)),
                ('extrovertido', models.CharField(max_length=2)),
                ('temeroso', models.CharField(max_length=2)),
                ('dominante', models.CharField(max_length=2)),
                ('impulsivo', models.CharField(max_length=2)),
                ('id_mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MatchApp.mascotas')),
            ],
        ),
        migrations.CreateModel(
            name='descripcion_mascota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexo', models.CharField(max_length=10)),
                ('tipo_pelo', models.CharField(max_length=10)),
                ('tamano_adulto', models.CharField(max_length=15)),
                ('peso_adulto', models.IntegerField()),
                ('alergias', models.CharField(max_length=2)),
                ('enfermedad_cronica', models.CharField(max_length=2)),
                ('esterilizado', models.CharField(max_length=2)),
                ('tratamiento', models.CharField(max_length=2)),
                ('id_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MatchApp.color')),
                ('id_mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MatchApp.mascotas')),
            ],
        ),
        migrations.AddField(
            model_name='albergues',
            name='id_distrito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MatchApp.distrito'),
        ),
    ]
