# Generated by Django 3.1.7 on 2021-03-14 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MatchApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albergues',
            name='ciudad',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='albergues',
            name='cuidador',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='albergues',
            name='dias_atencion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='albergues',
            name='direccion',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='albergues',
            name='duena',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='albergues',
            name='fecha_ingreso_matchcota',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='albergues',
            name='horario_atencion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='albergues',
            name='nombre_albergue',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='albergues',
            name='referencia',
            field=models.CharField(blank=True, max_length=11000, null=True),
        ),
        migrations.AlterField(
            model_name='albergues',
            name='responsable',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='albergues',
            name='vigente',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='color',
            name='nombre_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='descripcion_mascota',
            name='alergias',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='descripcion_mascota',
            name='enfermedad_cronica',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='descripcion_mascota',
            name='esterilizado',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='descripcion_mascota',
            name='peso_adulto',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='descripcion_mascota',
            name='sexo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='descripcion_mascota',
            name='tamano_adulto',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='descripcion_mascota',
            name='tipo_pelo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='descripcion_mascota',
            name='tratamiento',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='distrito',
            name='cod_postal',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='distrito',
            name='nombre_distrito',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='estado',
            name='estado',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mascotas',
            name='activo_web',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='mascotas',
            name='f_fallecimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mascotas',
            name='f_ingreso_albergue',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mascotas',
            name='f_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mascotas',
            name='f_registro_matchcota',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mascotas',
            name='microchip',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='mascotas',
            name='nombre_mascota',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mascotas',
            name='numero_carnet',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='mascotas',
            name='tipo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='personalidad_gato',
            name='amigable',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default=0, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='personalidad_gato',
            name='dominante',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default=0, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='personalidad_gato',
            name='extrovertido',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default=0, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='personalidad_gato',
            name='impulsivo',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default=0, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='personalidad_gato',
            name='sociable_humanos',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='personalidad_gato',
            name='temeroso',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default=0, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='personalidad_perro',
            name='carinoso',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default=0, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='personalidad_perro',
            name='curioso',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default=0, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='personalidad_perro',
            name='deportista',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default=0, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='personalidad_perro',
            name='educado',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default=0, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='personalidad_perro',
            name='independiente',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default=0, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='personalidad_perro',
            name='jugueton',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default=0, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='personalidad_perro',
            name='relacion_p_hembras',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='personalidad_perro',
            name='relacion_p_humanos',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='personalidad_perro',
            name='relacion_p_machos',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='personalidad_perro',
            name='tranquilo',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default=0, max_length=2, null=True),
        ),
    ]
