# Generated by Django 3.1.7 on 2021-03-14 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MatchApp', '0002_auto_20210314_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descripcion_mascota',
            name='alergias',
            field=models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='descripcion_mascota',
            name='enfermedad_cronica',
            field=models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='descripcion_mascota',
            name='esterilizado',
            field=models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='descripcion_mascota',
            name='tamano_adulto',
            field=models.CharField(blank=True, choices=[('P', 'Pequeno'), ('M', 'Mediano'), ('G', 'Grande')], default='Me', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='descripcion_mascota',
            name='tipo_pelo',
            field=models.CharField(blank=True, choices=[('L', 'Largo'), ('Me', 'Mediano'), ('C', 'Corto')], default='N', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='descripcion_mascota',
            name='tratamiento',
            field=models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='personalidad_gato',
            name='sociable_humanos',
            field=models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='personalidad_perro',
            name='relacion_p_hembras',
            field=models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='personalidad_perro',
            name='relacion_p_humanos',
            field=models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='personalidad_perro',
            name='relacion_p_machos',
            field=models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=2, null=True),
        ),
    ]
