# Generated by Django 3.1.7 on 2021-03-14 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MatchApp', '0003_auto_20210314_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albergues',
            name='id_distrito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MatchApp.distrito'),
        ),
    ]
