# Generated by Django 3.1.7 on 2021-03-14 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MatchApp', '0004_auto_20210314_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascotas',
            name='id_albergue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MatchApp.albergues'),
        ),
        migrations.AlterField(
            model_name='mascotas',
            name='id_estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MatchApp.estado'),
        ),
    ]
