# Generated by Django 3.1.7 on 2021-03-14 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MatchApp', '0005_auto_20210314_0343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascotas',
            name='numero_carnet',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
