# Generated by Django 3.1.7 on 2021-03-14 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MatchApp', '0007_auto_20210314_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descripcion_mascota',
            name='tamano_adulto',
            field=models.CharField(blank=True, choices=[('P', 'Pequeno'), ('M', 'Mediano'), ('G', 'Grande')], default='Me', max_length=10, null=True),
        ),
    ]
