# Generated by Django 3.1.7 on 2021-03-14 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MatchApp', '0008_auto_20210314_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descripcion_mascota',
            name='id_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MatchApp.color'),
        ),
        migrations.AlterField(
            model_name='descripcion_mascota',
            name='id_mascota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MatchApp.mascotas'),
        ),
    ]
