# Generated by Django 3.1.7 on 2021-03-14 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MatchApp', '0009_auto_20210314_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalidad_perro',
            name='carinoso',
            field=models.IntegerField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='personalidad_perro',
            name='curioso',
            field=models.IntegerField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='personalidad_perro',
            name='deportista',
            field=models.IntegerField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='personalidad_perro',
            name='educado',
            field=models.IntegerField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='personalidad_perro',
            name='independiente',
            field=models.IntegerField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='personalidad_perro',
            name='jugueton',
            field=models.IntegerField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='personalidad_perro',
            name='tranquilo',
            field=models.IntegerField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default=0, null=True),
        ),
    ]
