# Generated by Django 3.1.7 on 2021-03-14 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MatchApp', '0011_auto_20210314_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descripcion_mascota',
            name='alergias',
            field=models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], default='', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='descripcion_mascota',
            name='enfermedad_cronica',
            field=models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], default='', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='descripcion_mascota',
            name='esterilizado',
            field=models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], default='', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='descripcion_mascota',
            name='tamano_adulto',
            field=models.CharField(blank=True, choices=[('P', 'Pequeno'), ('M', 'Mediano'), ('G', 'Grande')], default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='descripcion_mascota',
            name='tipo_pelo',
            field=models.CharField(blank=True, choices=[('L', 'Largo'), ('Me', 'Mediano'), ('C', 'Corto'), ('SP', 'Sin Pelo')], default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='descripcion_mascota',
            name='tratamiento',
            field=models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], default='', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='mascotas',
            name='tipo',
            field=models.CharField(blank=True, choices=[('P', 'Perro'), ('G', 'Gato')], default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='personalidad_gato',
            name='amigable',
            field=models.IntegerField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default='', null=True),
        ),
        migrations.AlterField(
            model_name='personalidad_gato',
            name='dominante',
            field=models.IntegerField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default='', null=True),
        ),
        migrations.AlterField(
            model_name='personalidad_gato',
            name='extrovertido',
            field=models.IntegerField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default='', null=True),
        ),
        migrations.AlterField(
            model_name='personalidad_gato',
            name='impulsivo',
            field=models.IntegerField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default='', null=True),
        ),
        migrations.AlterField(
            model_name='personalidad_gato',
            name='sociable_humanos',
            field=models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], default='', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='personalidad_gato',
            name='temeroso',
            field=models.IntegerField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default='', null=True),
        ),
        migrations.AlterField(
            model_name='personalidad_perro',
            name='carinoso',
            field=models.IntegerField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default='', null=True),
        ),
        migrations.AlterField(
            model_name='personalidad_perro',
            name='curioso',
            field=models.IntegerField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default='', null=True),
        ),
        migrations.AlterField(
            model_name='personalidad_perro',
            name='deportista',
            field=models.IntegerField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default='', null=True),
        ),
        migrations.AlterField(
            model_name='personalidad_perro',
            name='educado',
            field=models.IntegerField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default='', null=True),
        ),
        migrations.AlterField(
            model_name='personalidad_perro',
            name='independiente',
            field=models.IntegerField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default='', null=True),
        ),
        migrations.AlterField(
            model_name='personalidad_perro',
            name='jugueton',
            field=models.IntegerField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default='', null=True),
        ),
        migrations.AlterField(
            model_name='personalidad_perro',
            name='relacion_p_hembras',
            field=models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], default='', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='personalidad_perro',
            name='relacion_p_humanos',
            field=models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], default='', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='personalidad_perro',
            name='relacion_p_machos',
            field=models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], default='', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='personalidad_perro',
            name='tranquilo',
            field=models.IntegerField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default='', null=True),
        ),
    ]
