# Generated by Django 3.1.7 on 2021-03-14 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MatchApp', '0013_auto_20210314_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascotas',
            name='tipo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
