# Generated by Django 3.1.7 on 2021-03-14 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MatchApp', '0014_auto_20210314_2236'),
    ]

    operations = [
        migrations.CreateModel(
            name='tipo_mascota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
