# Generated by Django 3.1.7 on 2021-03-15 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MatchApp', '0016_auto_20210315_2037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mascotas',
            old_name='tipo',
            new_name='id_tipo',
        ),
    ]
