# Generated by Django 3.1.7 on 2021-03-16 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MatchApp', '0017_auto_20210315_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descripcion_mascota',
            name='alergias',
            field=models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='descripcion_mascota',
            name='enfermedad_cronica',
            field=models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], max_length=20, null=True, verbose_name='enfermedad cronica'),
        ),
        migrations.AlterField(
            model_name='descripcion_mascota',
            name='esterilizado',
            field=models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='descripcion_mascota',
            name='id_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MatchApp.color', verbose_name='color'),
        ),
        migrations.AlterField(
            model_name='descripcion_mascota',
            name='peso_adulto',
            field=models.IntegerField(blank=True, null=True, verbose_name='Peso de Adulto'),
        ),
        migrations.AlterField(
            model_name='descripcion_mascota',
            name='sexo',
            field=models.CharField(blank=True, choices=[('Ma', 'Macho'), ('He', 'Hembra')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='descripcion_mascota',
            name='tamano_adulto',
            field=models.CharField(blank=True, choices=[('Pe', 'Pequeno'), ('Me', 'Mediano')], max_length=10, null=True, verbose_name='Tamano de Adulto'),
        ),
        migrations.AlterField(
            model_name='descripcion_mascota',
            name='tipo_pelo',
            field=models.CharField(blank=True, choices=[('La', 'Largo'), ('Med', 'Mediano'), ('Co', 'Corto'), ('SP', 'Sin Pelo')], max_length=10, null=True, verbose_name='tipo de Pelo'),
        ),
        migrations.AlterField(
            model_name='descripcion_mascota',
            name='tratamiento',
            field=models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='mascotas',
            name='activo_web',
            field=models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], max_length=20, null=True, verbose_name='Activo en Web'),
        ),
        migrations.AlterField(
            model_name='mascotas',
            name='f_fallecimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Fallecimiento'),
        ),
        migrations.AlterField(
            model_name='mascotas',
            name='f_ingreso_albergue',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Ingreso Albergue'),
        ),
        migrations.AlterField(
            model_name='mascotas',
            name='f_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fech de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='mascotas',
            name='f_registro_matchcota',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Registro en Matchcota'),
        ),
        migrations.AlterField(
            model_name='mascotas',
            name='id_albergue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MatchApp.albergues', verbose_name='Albergue'),
        ),
        migrations.AlterField(
            model_name='mascotas',
            name='id_estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MatchApp.estado', verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='mascotas',
            name='id_tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MatchApp.tipo_mascota', verbose_name='Tipo de Mascota'),
        ),
        migrations.AlterField(
            model_name='mascotas',
            name='nombre_mascota',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre Mascota'),
        ),
        migrations.AlterField(
            model_name='mascotas',
            name='numero_carnet',
            field=models.IntegerField(blank=True, null=True, verbose_name='Numero Carnet'),
        ),
        migrations.AlterField(
            model_name='personalidad_gato',
            name='amigable',
            field=models.IntegerField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], null=True),
        ),
        migrations.AlterField(
            model_name='personalidad_gato',
            name='dominante',
            field=models.IntegerField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], null=True),
        ),
        migrations.AlterField(
            model_name='personalidad_gato',
            name='extrovertido',
            field=models.IntegerField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], null=True),
        ),
        migrations.AlterField(
            model_name='personalidad_gato',
            name='impulsivo',
            field=models.IntegerField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], null=True),
        ),
        migrations.AlterField(
            model_name='personalidad_gato',
            name='sociable_humanos',
            field=models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='personalidad_gato',
            name='temeroso',
            field=models.IntegerField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], null=True),
        ),
        migrations.AlterField(
            model_name='personalidad_perro',
            name='carinoso',
            field=models.IntegerField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], null=True),
        ),
        migrations.AlterField(
            model_name='personalidad_perro',
            name='curioso',
            field=models.IntegerField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], null=True),
        ),
        migrations.AlterField(
            model_name='personalidad_perro',
            name='deportista',
            field=models.IntegerField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], null=True),
        ),
        migrations.AlterField(
            model_name='personalidad_perro',
            name='educado',
            field=models.IntegerField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], null=True),
        ),
        migrations.AlterField(
            model_name='personalidad_perro',
            name='independiente',
            field=models.IntegerField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], null=True),
        ),
        migrations.AlterField(
            model_name='personalidad_perro',
            name='jugueton',
            field=models.IntegerField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], null=True),
        ),
        migrations.AlterField(
            model_name='personalidad_perro',
            name='relacion_p_hembras',
            field=models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='personalidad_perro',
            name='relacion_p_humanos',
            field=models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='personalidad_perro',
            name='relacion_p_machos',
            field=models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='personalidad_perro',
            name='tranquilo',
            field=models.IntegerField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], null=True),
        ),
    ]
