# Generated by Django 3.1.7 on 2021-03-16 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MatchApp', '0018_auto_20210316_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descripcion_mascota',
            name='sexo',
            field=models.CharField(blank=True, choices=[('Ma', 'Macho'), ('He', 'Hembra')], max_length=7, null=True),
        ),
    ]
