# Generated by Django 3.1.7 on 2021-03-16 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MatchApp', '0019_auto_20210316_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descripcion_mascota',
            name='alergias',
            field=models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='descripcion_mascota',
            name='enfermedad_cronica',
            field=models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], max_length=20, null=True, verbose_name='enfermedad cronica'),
        ),
        migrations.AlterField(
            model_name='descripcion_mascota',
            name='esterilizado',
            field=models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='descripcion_mascota',
            name='tratamiento',
            field=models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='mascotas',
            name='activo_web',
            field=models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], max_length=20, null=True, verbose_name='Activo en Web'),
        ),
        migrations.AlterField(
            model_name='personalidad_perro',
            name='relacion_p_hembras',
            field=models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='personalidad_perro',
            name='relacion_p_humanos',
            field=models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='personalidad_perro',
            name='relacion_p_machos',
            field=models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], max_length=20, null=True),
        ),
    ]
