# Generated by Django 3.1.7 on 2021-03-16 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MatchApp', '0021_auto_20210316_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descripcion_mascota',
            name='alergias',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='descripcion_mascota',
            name='enfermedad_cronica',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=20, null=True, verbose_name='enfermedad cronica'),
        ),
        migrations.AlterField(
            model_name='descripcion_mascota',
            name='esterilizado',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='descripcion_mascota',
            name='sexo',
            field=models.CharField(blank=True, choices=[('Macho', 'Macho'), ('Hembra', 'Hembra')], max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='descripcion_mascota',
            name='tamano_adulto',
            field=models.CharField(blank=True, choices=[('Pequeno', 'Pequeno'), ('Mediano', 'Mediano')], max_length=10, null=True, verbose_name='Tamano de Adulto'),
        ),
        migrations.AlterField(
            model_name='descripcion_mascota',
            name='tipo_pelo',
            field=models.CharField(blank=True, choices=[('Largo', 'Largo'), ('Mediano', 'Mediano'), ('Corto', 'Corto'), ('Sin Pelo', 'Sin Pelo')], max_length=10, null=True, verbose_name='tipo de Pelo'),
        ),
        migrations.AlterField(
            model_name='descripcion_mascota',
            name='tratamiento',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='mascotas',
            name='activo_web',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=20, null=True, verbose_name='Activo en Web'),
        ),
    ]
