# Generated by Django 3.1.7 on 2021-03-19 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MatchApp', '0024_auto_20210319_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascotas',
            name='sociable_humanos',
            field=models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], max_length=3, null=True),
        ),
    ]
