# Generated by Django 3.1.7 on 2021-03-19 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MatchApp', '0026_auto_20210319_1315'),
    ]

    operations = [
        migrations.CreateModel(
            name='medio_contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='mascotas',
            name='carinoso',
            field=models.CharField(blank=True, choices=[('N/A', 'N/A'), ('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=3, null=True, verbose_name='cariñoso'),
        ),
        migrations.AlterField(
            model_name='mascotas',
            name='relacion_p_hembras',
            field=models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], max_length=20, null=True, verbose_name='Relacon con Hembras'),
        ),
        migrations.AlterField(
            model_name='mascotas',
            name='relacion_p_humanos',
            field=models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], max_length=20, null=True, verbose_name='Relacion con Humanos'),
        ),
        migrations.AlterField(
            model_name='mascotas',
            name='relacion_p_machos',
            field=models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], max_length=20, null=True, verbose_name='Relacion con Machos'),
        ),
        migrations.AlterField(
            model_name='mascotas',
            name='sociable_humanos',
            field=models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], max_length=3, null=True, verbose_name='Sociable con Humanos'),
        ),
    ]
