# Generated by Django 3.1.7 on 2021-03-20 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MatchApp', '0027_auto_20210319_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascotas',
            name='activo_web',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No'), ('N/A', 'N/A')], max_length=20, null=True, verbose_name='Activo en Web'),
        ),
        migrations.AlterField(
            model_name='mascotas',
            name='alergias',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No'), ('N/A', 'N/A')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='mascotas',
            name='enfermedad_cronica',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No'), ('N/A', 'N/A')], max_length=20, null=True, verbose_name='enfermedad cronica'),
        ),
        migrations.AlterField(
            model_name='mascotas',
            name='esterilizado',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No'), ('N/A', 'N/A')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='mascotas',
            name='relacion_p_hembras',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No'), ('N/A', 'N/A')], max_length=20, null=True, verbose_name='Relacon con Hembras'),
        ),
        migrations.AlterField(
            model_name='mascotas',
            name='relacion_p_humanos',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No'), ('N/A', 'N/A')], max_length=20, null=True, verbose_name='Relacion con Humanos'),
        ),
        migrations.AlterField(
            model_name='mascotas',
            name='relacion_p_machos',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No'), ('N/A', 'N/A')], max_length=20, null=True, verbose_name='Relacion con Machos'),
        ),
        migrations.AlterField(
            model_name='mascotas',
            name='sociable_humanos',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No'), ('N/A', 'N/A')], max_length=3, null=True, verbose_name='Sociable con Humanos'),
        ),
        migrations.AlterField(
            model_name='mascotas',
            name='tratamiento',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No'), ('N/A', 'N/A')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(blank=True, max_length=10, null=True)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('sexo', models.CharField(blank=True, choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=10, null=True)),
                ('nacionalidad', models.CharField(blank=True, max_length=50, null=True)),
                ('f_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('tel_fijo', models.CharField(blank=True, max_length=15, null=True, verbose_name='telefono fijo')),
                ('tel_cel', models.CharField(blank=True, max_length=15, null=True, verbose_name='Celular')),
                ('ocupacion', models.CharField(blank=True, max_length=30, null=True, verbose_name='Ocupacion')),
                ('centro_trabajo', models.CharField(blank=True, max_length=30, null=True, verbose_name='Centro de Trabajo')),
                ('direccion', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Direccion')),
                ('f_registro', models.DateField(blank=True, null=True, verbose_name='Fecha de Registro')),
                ('f_contacto', models.DateField(blank=True, null=True, verbose_name='Fecha de Contacto')),
                ('comentarios_internos', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Comentarios')),
                ('tipo_interes', models.CharField(blank=True, choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=17, null=True, verbose_name='Tipo de Interes')),
                ('tuvo_mascotas', models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No'), ('N/A', 'N/A')], max_length=4, null=True, verbose_name='Tuvo mascotas')),
                ('conocimiento_cuidados', models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No'), ('N/A', 'N/A')], max_length=4, null=True, verbose_name='Conocimiento de Cuidados')),
                ('sit_mascota_anterior', models.CharField(blank=True, choices=[('Lo regale', 'Lo regale'), ('Murio anciano', 'Murio anciano'), ('Murio de una enfermedad', 'Murio de una enfermedad'), ('Se perdio', 'Se perdio')], max_length=25, null=True, verbose_name='Situacion Masc_Ant')),
                ('motivo_adopcion', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Motivo de Adopcion')),
                ('detalle_conocimientos', models.CharField(blank=True, max_length=3000, null=True, verbose_name='Detalle de Conocimientos')),
                ('viaje_planeado', models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No'), ('N/A', 'N/A')], max_length=4, null=True, verbose_name='Viaje Planeado')),
                ('detalle_viaje', models.CharField(blank=True, max_length=3000, null=True, verbose_name='Detalle de Viaje')),
                ('tipo_fam', models.CharField(blank=True, choices=[('Familia', 'Familia'), ('Adulto(s)', 'Adulto(s)'), ('Joven <25', 'Joven <25'), ('Senior', 'Senior')], max_length=10, null=True, verbose_name='Tipo de Familia')),
                ('num_persona', models.CharField(blank=True, choices=[('N/A', 'N/A'), ('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=3, null=True, verbose_name='Numero de Personas')),
                ('alergico_pelo', models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No'), ('N/A', 'N/A')], max_length=4, null=True, verbose_name='Alergico al Pelo')),
                ('embarazadas', models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No'), ('N/A', 'N/A')], max_length=4, null=True, verbose_name='Embarazadas en casa')),
                ('num_mascotas_actual', models.CharField(blank=True, choices=[('N/A', 'N/A'), ('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=3, null=True, verbose_name='Numero de Mascotas Actual')),
                ('ninos', models.CharField(blank=True, choices=[('N/A', 'N/A'), ('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=3, null=True, verbose_name='Numero de ninos en casa')),
                ('horas_mascota_solo', models.CharField(blank=True, choices=[('N/A', 'N/A'), ('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=3, null=True, verbose_name='Horas mascota solo')),
                ('seguro_mascotas', models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No'), ('N/A', 'N/A')], max_length=4, null=True, verbose_name='Lugar Seguro')),
                ('tipo_viv', models.CharField(blank=True, choices=[('Casa', 'Casa'), ('Depa', 'Depa')], max_length=10, null=True, verbose_name='Tipo de Vivienda')),
                ('sit_viv', models.CharField(blank=True, choices=[('Propia', 'Propia'), ('Alquilada', 'Alquilada')], max_length=15, null=True, verbose_name='Situacion de Vivienda')),
                ('fumigado', models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No'), ('N/A', 'N/A')], max_length=4, null=True, verbose_name='Fumigado')),
                ('permiten_mascotas', models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No'), ('N/A', 'N/A')], max_length=4, null=True, verbose_name='Permiten Mascotas')),
                ('rejas_malla', models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No'), ('N/A', 'N/A')], max_length=4, null=True, verbose_name='Hay rejas/malla')),
                ('ventanas_calle', models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No'), ('N/A', 'N/A')], max_length=4, null=True, verbose_name='Vetanas a la calle')),
                ('ambientes_habilitados', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Ambientes Habilitados')),
                ('jardin_interno', models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No'), ('N/A', 'N/A')], max_length=4, null=True, verbose_name='Jardin interno')),
                ('jardin_externo', models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No'), ('N/A', 'N/A')], max_length=4, null=True, verbose_name='Jardin externo')),
                ('patio_interno', models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No'), ('N/A', 'N/A')], max_length=4, null=True, verbose_name='Patio')),
                ('responsable_directo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Responsable directo')),
                ('todos_acuerdo', models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No'), ('N/A', 'N/A')], max_length=4, null=True, verbose_name='Todos de acuerdo')),
                ('tiempo_dedicacion', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tiempo de dedicacion')),
                ('compromiso_mudanza', models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No'), ('N/A', 'N/A')], max_length=4, null=True, verbose_name='Compromiso en Mudanza')),
                ('compromiso_vida', models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No'), ('N/A', 'N/A')], max_length=4, null=True, verbose_name='Compromiso Vida')),
                ('compromiso_cuidado', models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No'), ('N/A', 'N/A')], max_length=4, null=True, verbose_name='Compromiso Cuidado')),
                ('compromiso_cuidado_imprescindible', models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No'), ('N/A', 'N/A')], max_length=4, null=True, verbose_name='Compromiso Cuidado Imprescindible')),
                ('txt_acuerdo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Acuerdo')),
                ('txttiempo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tiempo')),
                ('txtabandono', models.CharField(blank=True, max_length=100, null=True, verbose_name='Abandono')),
                ('txtcuidado1', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cuidado')),
                ('txtimpres', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cuidado Imprescindible')),
                ('txtvida', models.CharField(blank=True, max_length=100, null=True, verbose_name='Vida')),
                ('id_distrito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MatchApp.distrito', verbose_name='Distrito')),
                ('id_medio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MatchApp.medio_contacto', verbose_name='Medio de Contacto')),
            ],
        ),
    ]
