# Generated by Django 3.1.7 on 2021-03-20 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MatchApp', '0028_auto_20210320_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='centro_trabajo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Centro de Trabajo'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='ocupacion',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ocupacion'),
        ),
    ]
