# Generated by Django 3.1.7 on 2021-03-20 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MatchApp', '0030_auto_20210321_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='sit_mascota_anterior',
            field=models.CharField(blank=True, choices=[('Lo regale', 'Lo regale'), ('Murio anciano', 'Murio anciano'), ('Murio de una enfermedad', 'Murio de una enfermedad'), ('Se perdio', 'Se perdio')], max_length=50, null=True, verbose_name='Situacion Masc_Ant'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='tipo_interes',
            field=models.CharField(blank=True, choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=40, null=True, verbose_name='Tipo de Interes'),
        ),
    ]
