# Generated by Django 3.1.7 on 2021-03-20 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MatchApp', '0031_auto_20210321_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='sit_viv',
            field=models.CharField(blank=True, choices=[('Propia', 'Propia'), ('Alquilada', 'Alquilada')], max_length=30, null=True, verbose_name='Situacion de Vivienda'),
        ),
    ]
