# Generated by Django 3.1.7 on 2021-03-21 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MatchApp', '0036_auto_20210321_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='centro_trabajo',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Centro de Trabajo'),
        ),
    ]
