# Generated by Django 3.1.7 on 2021-03-21 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MatchApp', '0037_auto_20210321_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='sexo',
            field=models.CharField(blank=True, choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='tipo_interes',
            field=models.CharField(blank=True, choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer')], max_length=40, null=True, verbose_name='Tipo de Interes'),
        ),
    ]
