# Generated by Django 3.1.7 on 2021-03-21 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MatchApp', '0038_auto_20210321_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='email',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
