# Generated by Django 3.1.7 on 2021-03-21 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MatchApp', '0039_auto_20210321_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='horas_mascota_solo',
            field=models.IntegerField(blank=True, null=True, verbose_name='Horas mascota solo'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='num_mascotas_actual',
            field=models.IntegerField(blank=True, null=True, verbose_name='Numero de Mascotas Actual'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='num_persona',
            field=models.IntegerField(blank=True, null=True, verbose_name='Numero de Personas'),
        ),
    ]
