# Generated by Django 3.1.7 on 2021-03-21 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MatchApp', '0043_auto_20210321_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='centro_trabajo',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Centro de Trabajo'),
        ),
        migrations.AddField(
            model_name='persona',
            name='direccion',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Direccion'),
        ),
        migrations.AddField(
            model_name='persona',
            name='f_contacto',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Contacto'),
        ),
        migrations.AddField(
            model_name='persona',
            name='f_registro',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Registro'),
        ),
        migrations.AddField(
            model_name='persona',
            name='id_distrito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MatchApp.distrito', verbose_name='Distrito'),
        ),
        migrations.AddField(
            model_name='persona',
            name='ocupacion',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ocupacion'),
        ),
    ]
