# Generated by Django 3.1.7 on 2021-03-21 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MatchApp', '0044_auto_20210321_1841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='f_contacto',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='f_registro',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='id_distrito',
        ),
    ]
