# Generated by Django 3.1.7 on 2021-03-21 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MatchApp', '0045_auto_20210321_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='direccion',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Direccion'),
        ),
    ]
