# Generated by Django 3.1.7 on 2021-03-21 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MatchApp', '0047_persona_id_distrito'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='alergico_pelo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Alergico al Pelo'),
        ),
        migrations.AddField(
            model_name='persona',
            name='ambientes_habilitados',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Ambientes Habilitados'),
        ),
        migrations.AddField(
            model_name='persona',
            name='comentarios_internos',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Comentarios'),
        ),
        migrations.AddField(
            model_name='persona',
            name='compromiso_cuidado',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Compromiso Cuidado'),
        ),
        migrations.AddField(
            model_name='persona',
            name='compromiso_cuidado_imprescindible',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Compromiso Cuidado Imprescindible'),
        ),
        migrations.AddField(
            model_name='persona',
            name='compromiso_mudanza',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Compromiso en Mudanza'),
        ),
        migrations.AddField(
            model_name='persona',
            name='compromiso_vida',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Compromiso Vida'),
        ),
        migrations.AddField(
            model_name='persona',
            name='conocimiento_cuidados',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Conocimiento de Cuidados'),
        ),
        migrations.AddField(
            model_name='persona',
            name='detalle_conocimientos',
            field=models.CharField(blank=True, max_length=3000, null=True, verbose_name='Detalle de Conocimientos'),
        ),
        migrations.AddField(
            model_name='persona',
            name='detalle_viaje',
            field=models.CharField(blank=True, max_length=3000, null=True, verbose_name='Detalle de Viaje'),
        ),
        migrations.AddField(
            model_name='persona',
            name='embarazadas',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Embarazadas en casa'),
        ),
        migrations.AddField(
            model_name='persona',
            name='f_contacto',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Contacto'),
        ),
        migrations.AddField(
            model_name='persona',
            name='f_registro',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Registro'),
        ),
        migrations.AddField(
            model_name='persona',
            name='fumigado',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Fumigado'),
        ),
        migrations.AddField(
            model_name='persona',
            name='horas_mascota_solo',
            field=models.IntegerField(blank=True, null=True, verbose_name='Horas mascota solo'),
        ),
        migrations.AddField(
            model_name='persona',
            name='jardin_externo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Jardin externo'),
        ),
        migrations.AddField(
            model_name='persona',
            name='jardin_interno',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Jardin interno'),
        ),
        migrations.AddField(
            model_name='persona',
            name='motivo_adopcion',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Motivo de Adopcion'),
        ),
        migrations.AddField(
            model_name='persona',
            name='ninos',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Numero de ninos en casa'),
        ),
        migrations.AddField(
            model_name='persona',
            name='num_mascotas_actual',
            field=models.IntegerField(blank=True, null=True, verbose_name='Numero de Mascotas Actual'),
        ),
        migrations.AddField(
            model_name='persona',
            name='num_persona',
            field=models.IntegerField(blank=True, null=True, verbose_name='Numero de Personas'),
        ),
        migrations.AddField(
            model_name='persona',
            name='patio_interno',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Patio'),
        ),
        migrations.AddField(
            model_name='persona',
            name='permiten_mascotas',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Permiten Mascotas'),
        ),
        migrations.AddField(
            model_name='persona',
            name='rejas_malla',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Hay rejas/malla'),
        ),
        migrations.AddField(
            model_name='persona',
            name='responsable_directo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Responsable directo'),
        ),
        migrations.AddField(
            model_name='persona',
            name='seguro_mascotas',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Lugar Seguro'),
        ),
        migrations.AddField(
            model_name='persona',
            name='sit_mascota_anterior',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Situacion Masc_Ant'),
        ),
        migrations.AddField(
            model_name='persona',
            name='sit_viv',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Situacion de Vivienda'),
        ),
        migrations.AddField(
            model_name='persona',
            name='tiempo_dedicacion',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tiempo de dedicacion'),
        ),
        migrations.AddField(
            model_name='persona',
            name='tipo_fam',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de Familia'),
        ),
        migrations.AddField(
            model_name='persona',
            name='tipo_interes',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de Interes'),
        ),
        migrations.AddField(
            model_name='persona',
            name='tipo_viv',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de Vivienda'),
        ),
        migrations.AddField(
            model_name='persona',
            name='todos_acuerdo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Todos de acuerdo'),
        ),
        migrations.AddField(
            model_name='persona',
            name='tuvo_mascotas',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tuvo mascotas'),
        ),
        migrations.AddField(
            model_name='persona',
            name='txt_acuerdo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Acuerdo'),
        ),
        migrations.AddField(
            model_name='persona',
            name='txtabandono',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Abandono'),
        ),
        migrations.AddField(
            model_name='persona',
            name='txtcuidado1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cuidado'),
        ),
        migrations.AddField(
            model_name='persona',
            name='txtimpres',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cuidado Imprescindible'),
        ),
        migrations.AddField(
            model_name='persona',
            name='txttiempo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tiempo'),
        ),
        migrations.AddField(
            model_name='persona',
            name='txtvida',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Vida'),
        ),
        migrations.AddField(
            model_name='persona',
            name='ventanas_calle',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Vetanas a la calle'),
        ),
        migrations.AddField(
            model_name='persona',
            name='viaje_planeado',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Viaje Planeado'),
        ),
    ]
