# Generated by Django 3.1.7 on 2021-03-21 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MatchApp', '0048_auto_20210321_1916'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='txt_acuerdo',
            new_name='txtacuerdo',
        ),
        migrations.AlterField(
            model_name='persona',
            name='alergico_pelo',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No'), ('N/A', 'N/A')], max_length=4, null=True, verbose_name='Alergico al Pelo'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='compromiso_cuidado',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No'), ('N/A', 'N/A')], max_length=4, null=True, verbose_name='Compromiso Cuidado'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='compromiso_cuidado_imprescindible',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No'), ('N/A', 'N/A')], max_length=4, null=True, verbose_name='Compromiso Cuidado Imprescindible'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='compromiso_mudanza',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No'), ('N/A', 'N/A')], max_length=4, null=True, verbose_name='Compromiso en Mudanza'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='compromiso_vida',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No'), ('N/A', 'N/A')], max_length=4, null=True, verbose_name='Compromiso Vida'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='conocimiento_cuidados',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No'), ('N/A', 'N/A')], max_length=4, null=True, verbose_name='Conocimiento de Cuidados'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='embarazadas',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No'), ('N/A', 'N/A')], max_length=4, null=True, verbose_name='Embarazadas en casa'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='fumigado',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No'), ('N/A', 'N/A')], max_length=4, null=True, verbose_name='Fumigado'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='jardin_externo',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No'), ('N/A', 'N/A')], max_length=4, null=True, verbose_name='Jardin externo'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='jardin_interno',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No'), ('N/A', 'N/A')], max_length=4, null=True, verbose_name='Jardin interno'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='ninos',
            field=models.CharField(blank=True, choices=[('N/A', 'N/A'), ('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=3, null=True, verbose_name='Numero de ninos en casa'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='patio_interno',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No'), ('N/A', 'N/A')], max_length=4, null=True, verbose_name='Patio'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='permiten_mascotas',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No'), ('N/A', 'N/A')], max_length=4, null=True, verbose_name='Permiten Mascotas'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='rejas_malla',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No'), ('N/A', 'N/A')], max_length=4, null=True, verbose_name='Hay rejas/malla'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='seguro_mascotas',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No'), ('N/A', 'N/A')], max_length=4, null=True, verbose_name='Lugar Seguro'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='sit_mascota_anterior',
            field=models.CharField(blank=True, choices=[('Lo regale', 'Lo regale'), ('Murio anciano', 'Murio anciano'), ('Murio de una enfermedad', 'Murio de una enfermedad'), ('Se perdio', 'Se perdio')], max_length=50, null=True, verbose_name='Situacion Masc_Ant'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='sit_viv',
            field=models.CharField(blank=True, choices=[('Propia', 'Propia'), ('Alquilada', 'Alquilada')], max_length=30, null=True, verbose_name='Situacion de Vivienda'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='tipo_fam',
            field=models.CharField(blank=True, choices=[('Familia', 'Familia'), ('Adulto(s)', 'Adulto(s)'), ('Joven <25', 'Joven <25'), ('Senior', 'Senior')], max_length=20, null=True, verbose_name='Tipo de Familia'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='tipo_interes',
            field=models.CharField(blank=True, choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer')], max_length=40, null=True, verbose_name='Tipo de Interes'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='tipo_viv',
            field=models.CharField(blank=True, choices=[('Casa', 'Casa'), ('Depa', 'Depa')], max_length=20, null=True, verbose_name='Tipo de Vivienda'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='todos_acuerdo',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No'), ('N/A', 'N/A')], max_length=4, null=True, verbose_name='Todos de acuerdo'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='tuvo_mascotas',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No'), ('N/A', 'N/A')], max_length=4, null=True, verbose_name='Tuvo mascotas'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='ventanas_calle',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No'), ('N/A', 'N/A')], max_length=4, null=True, verbose_name='Vetanas a la calle'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='viaje_planeado',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No'), ('N/A', 'N/A')], max_length=4, null=True, verbose_name='Viaje Planeado'),
        ),
    ]
