# Generated by Django 3.1.7 on 2021-03-21 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MatchApp', '0049_auto_20210321_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='compromiso_cuidado_imprescindible',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='txtimpres',
        ),
        migrations.AlterField(
            model_name='persona',
            name='compromiso_mudanza',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No'), ('N/A', 'N/A')], max_length=4, null=True, verbose_name='Compromiso de no Abandono'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='tiempo_dedicacion',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No'), ('N/A', 'N/A')], max_length=4, null=True, verbose_name='Compromiso de Tiempo de dedicacion'),
        ),
    ]
