# Generated by Django 3.1.7 on 2021-03-21 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MatchApp', '0050_auto_20210321_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='tipo_interes',
            field=models.CharField(blank=True, choices=[('Adoptante', 'Adoptante'), ('Padrino/Madrina', 'Padrino/Madrina')], max_length=40, null=True, verbose_name='Tipo de Interes'),
        ),
    ]
