# Generated by Django 3.1.7 on 2021-05-07 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MatchApp', '0052_detalle_puesto_entrevista_equipo_matchcota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrevista',
            name='puntuacion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True, verbose_name='Puntuacion'),
        ),
    ]
