# Generated by Django 3.1.7 on 2021-05-08 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MatchApp', '0053_auto_20210507_2355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entrevista',
            old_name='Comentarios_entrevista',
            new_name='comentarios_entrevista',
        ),
        migrations.AlterField(
            model_name='entrevista',
            name='puntuacion',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Puntuacion'),
        ),
    ]
