# Generated by Django 3.1.7 on 2021-05-08 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MatchApp', '0054_auto_20210509_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrevista',
            name='comentarios_entrevista',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Comentarios'),
        ),
    ]
