# Generated by Django 3.1.7 on 2021-05-08 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MatchApp', '0056_auto_20210509_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrevista',
            name='puntuacion',
            field=models.CharField(blank=True, choices=[('N/A', 'N/A'), ('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=3, null=True, verbose_name='Puntuacion'),
        ),
    ]
