# Generated by Django 3.1.7 on 2021-05-09 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MatchApp', '0059_auto_20210509_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adopciones',
            name='tipo',
            field=models.CharField(blank=True, choices=[('Adopción', 'Adopción'), ('Intento', 'Intento')], max_length=20, null=True, verbose_name='Tipo de Proceso'),
        ),
        migrations.CreateModel(
            name='seguimiento_adopciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_seguimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Seguimiento')),
                ('comentarios', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Comentario')),
                ('id_adopcion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MatchApp.adopciones', verbose_name='Adopcion')),
            ],
        ),
    ]
