# Generated by Django 3.1.7 on 2021-05-12 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MatchApp', '0063_auto_20210511_2335'),
    ]

    operations = [
        migrations.CreateModel(
            name='devolucione',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_devolucion', models.DateField(blank=True, null=True, verbose_name='Fecha de devolucion')),
                ('comentarios', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Comentarios')),
                ('motivo', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Motivo')),
                ('id_adopcion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MatchApp.adopciones', verbose_name='Adopcion')),
            ],
        ),
    ]
