# Generated by Django 3.1.7 on 2021-05-12 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MatchApp', '0064_devolucione'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devolucione',
            name='motivo',
            field=models.CharField(blank=True, choices=[('EM', 'Enfermedad Mascota'), ('PPA', 'Problemas Personales del Adoptante'), ('PMA', 'Personalidad Mascota'), ('RCA', 'Relacion con Adoptantes'), ('RCM', 'Relacion con otras Mascotas')], max_length=20, null=True, verbose_name='Motivo'),
        ),
    ]
