# Generated by Django 3.1.7 on 2021-05-12 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MatchApp', '0066_auto_20210512_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apadrinamiento',
            name='dia_pago',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('0', '3'), ('0', '4'), ('0', '5'), ('0', '6'), ('0', '7'), ('0', '8'), ('0', '9'), ('0', '10'), ('0', '11'), ('0', '12'), ('0', '13'), ('0', '14'), ('0', '15'), ('0', '16'), ('0', '17'), ('0', '18'), ('0', '19'), ('0', '20'), ('0', '21'), ('0', '22'), ('0', '23'), ('0', '24'), ('0', '25'), ('0', '26'), ('0', '27'), ('0', '28'), ('0', '29'), ('0', '30'), ('0', '31')], max_length=20, null=True, verbose_name='Dia de pago'),
        ),
        migrations.AlterField(
            model_name='devolucione',
            name='motivo',
            field=models.CharField(blank=True, choices=[('Enfermedad Mascota', 'Enfermedad Mascota'), ('Problemas Personales del Adoptante', 'Problemas Personales del Adoptante'), ('Personalidad Mascota', 'Personalidad Mascota'), ('Relacion con Adoptantes', 'Relacion con Adoptantes'), ('Relacion con otras Mascotas', 'Relacion con otras Mascotas'), ('Otros', 'Otros')], max_length=100, null=True, verbose_name='Motivo'),
        ),
        migrations.AlterField(
            model_name='entrevista',
            name='puntuacion',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=3, null=True, verbose_name='Puntuacion'),
        ),
        migrations.AlterField(
            model_name='mascotas',
            name='amigable',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='mascotas',
            name='carinoso',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=3, null=True, verbose_name='cariñoso'),
        ),
        migrations.AlterField(
            model_name='mascotas',
            name='curioso',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='mascotas',
            name='deportista',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='mascotas',
            name='dominante',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='mascotas',
            name='educado',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='mascotas',
            name='extrovertido',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='mascotas',
            name='impulsivo',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='mascotas',
            name='independiente',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='mascotas',
            name='jugueton',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='mascotas',
            name='temeroso',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='mascotas',
            name='tranquilo',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='ninos',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=3, null=True, verbose_name='Numero de ninos en casa'),
        ),
    ]
