# Generated by Django 3.1.7 on 2021-05-12 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MatchApp', '0068_auto_20210512_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devolucione',
            name='motivo',
            field=models.CharField(blank=True, choices=[('Enfermedad mascota', 'Enfermedad mascota'), ('Problemas personales del adoptante', 'Problemas personales del adoptante'), ('Personalidad mascota', 'Personalidad mascota'), ('Relacion con adoptantes', 'Relacion con adoptantes'), ('Relacion con otras mascotas', 'Relacion con otras mascotas'), ('Otros', 'Otros')], max_length=100, null=True, verbose_name='Motivo'),
        ),
    ]
