# Generated by Django 3.1.7 on 2021-05-16 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimientoApp', '0001_initial'),
        ('MatchApp', '0069_auto_20210512_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo_matchcota',
            name='id_distrito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mantenimientoApp.distrito', verbose_name='Distrito'),
        ),
        migrations.AlterField(
            model_name='mascotas',
            name='id_albergue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mantenimientoApp.albergues', verbose_name='Albergue'),
        ),
        migrations.AlterField(
            model_name='mascotas',
            name='id_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mantenimientoApp.color', verbose_name='color'),
        ),
        migrations.AlterField(
            model_name='mascotas',
            name='id_estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mantenimientoApp.estado', verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='mascotas',
            name='id_tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mantenimientoApp.tipo_mascota', verbose_name='Tipo de Mascota'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='id_distrito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mantenimientoApp.distrito', verbose_name='Distrito'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='id_medio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mantenimientoApp.medio_contacto', verbose_name='Medio de Contacto'),
        ),
        migrations.DeleteModel(
            name='albergues',
        ),
        migrations.DeleteModel(
            name='color',
        ),
        migrations.DeleteModel(
            name='distrito',
        ),
        migrations.DeleteModel(
            name='estado',
        ),
        migrations.DeleteModel(
            name='medio_contacto',
        ),
        migrations.DeleteModel(
            name='tipo_mascota',
        ),
    ]
