# Generated by Django 3.1.7 on 2021-05-16 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mantenimientoApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='equipo_matchcota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=254, null=True, verbose_name='Nombre')),
                ('condicion', models.CharField(blank=True, choices=[('Voluntario', 'Voluntario'), ('Staff permanente', 'Staff permanente'), ('Fundador', 'Fundador'), ('Contratado', 'Contratado'), ('Fundador/Staff permanente', 'Fundador/Staff permanente')], max_length=50, null=True, verbose_name='Condicion')),
                ('dni', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=254, null=True, verbose_name='email Personal')),
                ('email_matchcota', models.CharField(blank=True, max_length=254, null=True, verbose_name='email_Matchcota')),
                ('tel_celular', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telefono celular')),
                ('f_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('nacionalidad', models.CharField(blank=True, max_length=10, null=True, verbose_name='telefono fijo')),
                ('direccion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Direccion')),
                ('estudios_cursados', models.CharField(blank=True, max_length=100, null=True, verbose_name='Estudios')),
                ('ocupacion', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ocupacion')),
                ('empresa', models.CharField(blank=True, max_length=100, null=True, verbose_name='Empresa')),
                ('t_coche', models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No'), ('N/A', 'N/A')], max_length=20, null=True, verbose_name='Tiene coche')),
                ('visito_albergue', models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No'), ('N/A', 'N/A')], max_length=20, null=True, verbose_name='Visito Albergue')),
                ('f_ingreso', models.DateField(blank=True, null=True, verbose_name='Fecha de Ingreso')),
                ('f_cese', models.DateField(blank=True, null=True, verbose_name='Fecha de Cese')),
                ('id_detalle_puesto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mantenimientoApp.detalle_puesto', verbose_name='Puesto')),
                ('id_distrito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mantenimientoApp.distrito', verbose_name='Distrito')),
            ],
        ),
    ]
